### ISSUE TITLE
Cannot save bcolz data from csv.gz, blaze.Data, or pandas.DataFrame

### ISSUE THREAD

**Issue by ltransom** [blaze/odo#291]
Have a data shape that uses string, int64, float64, and datetime.

Cannot covert a test.csv.gz file to .bcolz from different different sources:
    *  csv.gz file
    *  .csv.gz file loaded into a blaze.Data
    *  .csv.gz file loaded into a pandas.DataFrame

Have test script and data to reproduce errors.

**Comment by cpcloud** [comment]
@ltransom see #181, #186, #253. bcolz has terrible support for object dtypes. can you try with a fixed length string dshape in your string column?

**Comment by cpcloud** [comment]
This should be fixed by https://github.com/Blosc/bcolz/pull/244

**Comment by cpcloud** [comment]
Can you give it a go and if it works close the issue?

**Comment by ltransom** [comment]
Two of the three test scenarios pass now:

odo(.csv.gz, .bcolz)  - works
odo(pandas.DataFrame, .bcolz) - works
odo(blaze.Data, .bcolz) - still fails
   ValueError: could not broadcast input array from shape (99999) into shape (3)

The data shape:
ds_fixed = dshape("var * { TradeTime: datetime, \
  Symbol: string[10, 'A'], \
  Price: float64, \
  Shares: int64, \
  Exchange: string[2, 'A'], \
  Sales: string[5, 'A'], \
  Sequence: int64, \
  Bid: float64, \
  Ask: float64, \
  BSize: int64, \
  ASize: int64 \
  }")

**Comment by cpcloud** [comment]
@ltransom awesome! thanks for trying this out .... checking out the last case in a bit

**Comment by cpcloud** [comment]
@ltransom how did you construct the `blaze.Data` object?

**Comment by ltransom** [comment]
from odo import odo, drop
from blaze import dshape, Data, Symbol, compute, resource
import pandas as pd
import os
from shutil import rmtree

TEST_PATH = "../../nobackup/test/"
TEST_BASE = "test"
TEST_NAME = TEST_PATH + TEST_BASE


ds_fixed = dshape("var * { TradeTime: datetime, \
  Symbol: string[10, 'A'], \
  Price: float64, \
  Shares: int64, \
  Exchange: string[2, 'A'], \
  Sales: string[5, 'A'], \
  Sequence: int64, \
  Bid: float64, \
  Ask: float64, \
  BSize: int64, \
  ASize: int64 \
  }")

def test_bcolz_data():
  src_name = TEST_NAME + ".csv.gz"
  tgt_name = TEST_NAME + ".bcolz"

  if os.path.exists(tgt_name):
    # drop(tgt_name)
    rmtree(tgt_name)
  bdf = Data(src_name)
  odo(bdf, tgt_name, dshape=ds_fixed)

  assert compute(Symbol('trades', ds_fixed).nrows, resource(tgt_name)) == 99999

**Comment by ltransom** [comment]
Using the same test data file I sent you.

**Comment by cpcloud** [comment]
@ltransom I just tried this against bcolz master and everything works. You'll have to install bcolz master. You can either clone and install from source or use `pip install git+git://github.com/Blosc/bcolz` (requires Cython [`conda install cython -y`]).
